### ISSUE TITLE
[Feature] Order First Vote by Vote Result

### ISSUE THREAD

**Issue by Fingolf6455** [FabianVolkers/face-the-facts-app#138]
**Is your feature request related to a problem? Please describe.**
As a user I want to easily see how the direct candidates performed last election, so I can make the most out of my vote.

**Describe the solution you'd like**
Order the candidates by percentage with the highest being at the top.

**Describe alternatives you've considered**

**Links:**
Figma:
Miro:

**Additional context**
Pretty much like this
<img width="411" alt="Bildschirmfoto 2021-06-17 um 12 17 11" src="https://user-images.githubusercontent.com/72171703/122378120-f55b9b00-cf65-11eb-8ec8-f5de1779a839.png">

**Comment by takahiromitsui** [comment]
@Urhengulas  will implement this functionality from backend
