### ISSUE TITLE
[Feature] Order Second Vote by list Positions

### ISSUE THREAD

**Issue by Fingolf6455** [FabianVolkers/face-the-facts-app#139]
**Is your feature request related to a problem? Please describe.**
As a User I want to know the other candidates I would support with my vote on the state list and if the candidate on which profile I am has even a chance.

**Describe the solution you'd like**
Order Second Vote List by the List Positions of the candidates.

**Describe alternatives you've considered**

**Links:**
Figma:
Miro:

**Additional context**
Pretty much like that (excluding that the first one is always blue)
<img width="413" alt="Bildschirmfoto 2021-06-17 um 12 19 32" src="https://user-images.githubusercontent.com/72171703/122378488-49ff1600-cf66-11eb-8e9e-f3806627ece3.png">
.

**Comment by takahiromitsui** [comment]
@Urhengulas will implement this functionality from the backend.
