### ISSUE TITLE
[Feature] Infinity Scroll Landesliste

### ISSUE THREAD

**Issue by Fingolf6455** [FabianVolkers/face-the-facts-app#152]
**Is your feature request related to a problem? Please describe.**
As a User I want to see all the candidates on the state list, so I can get a better picture who I also support potentially with my vote and who the candidate has as a political friend.

**Describe the solution you'd like**
If you scroll to the button of the "Landesliste" and there are more people to display they should load automatically to a certain degree (e.g. next ten when the user scrolls.

**Describe alternatives you've considered**
Installing a "more" button that does the same but more manually or displaying all the candidates from the very start.

**Comment by RichardKruemmel** [comment]
Issue is redundant as we fetch the whole StatesList
