### ISSUE TITLE
[Feature] Second Vote Pop-Up if not on List

### ISSUE THREAD

**Issue by Fingolf6455** [FabianVolkers/face-the-facts-app#159]
**Is your feature request related to a problem? Please describe.**
As a User I want a visual indicator, that the candidate is not on the state list, so I can be sure, it's not a bug.

**Describe the solution you'd like**
Currently when the candidate is not on the list it breaks the program.
Instead we should display a simple Pop-Up when the User visits the Second Vote Tab.

**Describe alternatives you've considered**

**Links:**
Figma:
Miro:

**Additional context**
 
![Bildschirmfoto_2021-06-21_um_10 26 26](https://user-images.githubusercontent.com/72171703/123645777-e9ee5680-d826-11eb-8fb0-2c3cdbbb29b2.png)

**Comment by takahiromitsui** [comment]
This issue was solved on #158
