### ISSUE TITLE
[Bug] search bar: result null

### ISSUE THREAD

**Issue by takahiromitsui** [FabianVolkers/face-the-facts-app#176]
**Describe the bug**
If a user types in a random letter like "zzz", an API doesn't return any results (null) and break this app.
**Photo**
![Screenshot 2021-07-01 at 09 41 37](https://user-images.githubusercontent.com/78789212/124085657-8d6e7f80-da50-11eb-9268-f5427379f7d5.png)

**Comment by Fingolf6455** [comment]
Can you check it also for "Baerbock" and "Bär"?
