### ISSUE TITLE
[Bug] Search Bar Up

### ISSUE THREAD

**Issue by Fingolf6455** [FabianVolkers/face-the-facts-app#178]
**Describe the bug**
Currently the Search Bar is on the Web is not working properly. The User has to double click the animation to search.

**To Reproduce**

1. Go to beta.facethefacts.app
2. Click on "Zur Demo"
3. Click on the search bar

**Expected behavior**
The Search Bar is instead fixated to the top and the search icon is present with the text being responsive on every device

**Screenshots**
<img width="555" alt="Bildschirmfoto 2021-07-01 um 11 46 27" src="https://user-images.githubusercontent.com/72171703/124103971-18a44100-da62-11eb-93da-3e4d4dd995e5.png">

**Additional context**

**Comment by takahiromitsui** [comment]
This issue was solved in #180
