### ISSUE TITLE
[Bug] Too long name for second Vote

### ISSUE THREAD

**Issue by Fingolf6455** [FabianVolkers/face-the-facts-app#197]
**Describe the bug**
Sometimes when a poltician has a too long name it doesn't fit in the second vote.

**Expected behavior**
The size of the letters become smaller so the name fits.

**Example**

![WhatsApp Image 2021-07-21 at 10 51 58 (1)](https://user-images.githubusercontent.com/72171703/126461520-e42cd49a-ad96-4df6-95de-e2c158d4d66e.jpeg)

**Comment by takahiromitsui** [comment]
Added media query to fit "69a789f".
