### ISSUE TITLE
[Feature] Space beetween Sidejobs Title and Votes

### ISSUE THREAD

**Issue by Fingolf6455** [FabianVolkers/face-the-facts-app#199]
**Is your feature request related to a problem? Please describe.**
The titles on the profile screen are very dense together and space beetween them is irregular.

**Describe the solution you'd like**
Give them all a little bit more room and make the space between content and headline and headline and other content the same.

![WhatsApp Image 2021-07-21 at 10 51 58 (2)](https://user-images.githubusercontent.com/72171703/126461661-9ebf3130-4028-49e7-9231-d1065624bda3.jpeg)

**Comment by takahiromitsui** [comment]
Fixed a026722 and c40211c
