### ISSUE TITLE
[Feature] Ion Chip text responsiveness 

### ISSUE THREAD

**Issue by Fingolf6455** [FabianVolkers/face-the-facts-app#200]
**Describe the solution you would like.**

Can we make the content of the ion Chips responsive? 
So that it gets smaller when the content is too long?

**Comment by Fingolf6455** [comment]
Here to clarify:
Currently we have a lot candidates with an occupation that extends the chip. So either we make the text smaller or the ion chip automatically little bit bigger.


![WhatsApp Image 2021-07-21 at 10 36 24](https://user-images.githubusercontent.com/72171703/126459140-b1a70725-33cf-4708-959e-2218b47e6d3a.jpeg)

**Comment by takahiromitsui** [comment]
Added responsiveness "7102974".
