### ISSUE TITLE
[Bug] Profile Header Cut

### ISSUE THREAD

**Issue by Fingolf6455** [FabianVolkers/face-the-facts-app#208]
**Describe the bug**
When there's too much content on the profile header like a too long name or a lot of occupation the whole profile moves itself up resulting in it leaving th page

**To Reproduce**

1. Go to "Annegret Kramp-Karrenbauer"
2. See bug

**Expected behavior**
The Positions of the Picture and the text is more responsive and adjusts to the content displayed. This is especially important as Annegret is a candidate in the upcoming election.

**Screenshots**
![WhatsApp Image 2021-07-21 at 10 51 58 (3)](https://user-images.githubusercontent.com/72171703/126463469-3943f77a-70b5-4dc6-ae0a-5ba166df10d1.jpeg)

**Comment by takahiromitsui** [comment]
Fix at 4122c76
