### ISSUE TITLE
[Bug] Green Party on Landesliste

### ISSUE THREAD

**Issue by Fingolf6455** [FabianVolkers/face-the-facts-app#209]
**Describe the bug**
The Green Party is displayed as Bündnis 90/Die Grünen on the Zweitstimmen Tab.

**To Reproduce**

1. Go to "Annalena Baerbock"
2. Click on 'Zweitstimme'
3. See error

**Expected behavior**
Display "Die Grünen" like everywhere else.

**Screenshots**
![WhatsApp Image 2021-07-21 at 11 38 35](https://user-images.githubusercontent.com/72171703/126467777-1192a56a-ac12-469b-a8e0-359225800c6c.jpeg)

**Comment by RichardKruemmel** [comment]
#206 fixed the issue
