### ISSUE TITLE
[Feature] CSU Party Icon

### ISSUE THREAD

**Issue by Fingolf6455** [FabianVolkers/face-the-facts-app#217]
**Is your feature request related to a problem? Please describe.**
As a User I want to easily identify the CSU party through its colors.

**Describe the solution you'd like**
Implement CSU colors like in the in the screenshot below

**Describe alternatives you've considered**
None.

**Links:**
Figma: https://www.figma.com/file/fOjTcQeptb7a4rTqPsSY5J/May-21?node-id=3201%3A12387

**Additional context**
<img width="362" alt="Bildschirmfoto 2021-07-28 um 08 56 44" src="https://user-images.githubusercontent.com/72171703/127278179-b2c66079-8818-4029-b4a5-82fbb192457e.png">

**Comment by takahiromitsui** [comment]
Implemented at 70e7955
