### ISSUE TITLE
[Bug] Vote Detail Vote Result

### ISSUE THREAD

**Issue by Fingolf6455** [FabianVolkers/face-the-facts-app#219]
**Describe the bug**
"Antrag angenommen" or "Antrag abgelehnt" are black.

**To Reproduce**

1. Go to 'Jens Spahn'
2. Click on a 'Vote'

**Expected behavior**
The letters should be white.

**Screenshots**
![WhatsApp Image 2021-07-28 at 09 24 04](https://user-images.githubusercontent.com/72171703/127281336-473a1bb8-082a-4c3b-b37b-85d274da0524.jpeg)

**Comment by RichardKruemmel** [comment]
This is WebView Bug and related to the React Native repo
