### ISSUE TITLE
[Bug] Kandidat:innen Landesliste last eection

### ISSUE THREAD

**Issue by Fingolf6455** [FabianVolkers/face-the-facts-app#224]
**Describe the bug**
The amount of candidates that last time came in over the state list is not featured.

**To Reproduce**

1. Go to Amhtor
2. Click on Wahlchancen
3. Click on Zweitstimme

**Expected behavior**
Show the amount of candidates that made it in the parliament through the list ist time.
Also change the wording to 
"Über diese Liste kamen letzte Wahl ... Kandidat:innen ins Parlament".

If you can not fix it get rid of it.

**Screenshots**
![WhatsApp Image 2021-07-30 at 13 00 53](https://user-images.githubusercontent.com/72171703/127643988-081005e1-b4fd-4a14-9f42-5205babd277e.jpeg)

**Comment by RichardKruemmel** [comment]
Fixed with https://github.com/FaceTheFacts/backend/pull/45
