### ISSUE TITLE
[Bug] Erststimme Wording

### ISSUE THREAD

**Issue by Fingolf6455** [FabianVolkers/face-the-facts-app#225]
**Describe the bug**
Currently when a politician doesn't have an Erststimme last election it says he doesn't have one this election. 
Also we have a lot of polticians that were direct candidates but aren't featured as one e.g. Jens Spahn

**To Reproduce**

1. Go to Jens Spahn
2. Click on Wahlchancen
3. See error

**Expected behavior**
Show the last Direct Votes results of the candidate from the last election.

Also change wording into "Wahlergebnis letzte Wahl"

If the candidate wasn't a direct candidate in the last election display:
"Nicht direkt wählbar
Diese:r Kandidat:in war bei der letzten Wahl nicht direkt wählbar." 

**Screenshots**
![WhatsApp Image 2021-07-30 at 13 00 46 (1)](https://user-images.githubusercontent.com/72171703/127644760-2a320648-656a-4d19-b2bb-900f3d4dbadd.jpeg)
![WhatsApp Image 2021-07-30 at 13 00 24](https://user-images.githubusercontent.com/72171703/127644762-3ae91abb-5f18-4cfe-afa2-b1cc7fba0ff9.jpeg)

**Comment by takahiromitsui** [comment]
Fix at ca3f9a3
