### ISSUE TITLE
[Bug] Landesliste Party Bug

### ISSUE THREAD

**Issue by Fingolf6455** [FabianVolkers/face-the-facts-app#226]
**Describe the bug**
There is a space between the party name and the Landesliste missing.

**To Reproduce**

1. Go to Amthor
2. Click on Wahlchancen
3. Click on Zweitstimme

**Expected behavior**
Have a space between Partyname and Landesliste.

**Screenshots**
![WhatsApp Image 2021-07-30 at 13 01 09](https://user-images.githubusercontent.com/72171703/127645257-b77f0b63-41df-46a2-a786-9757fa7ce9e4.jpeg)

**Comment by RichardKruemmel** [comment]
Fixed with https://github.com/FaceTheFacts/backend/pull/45
