### ISSUE TITLE
[Bug] Not on Landesliste display

### ISSUE THREAD

**Issue by Fingolf6455** [FabianVolkers/face-the-facts-app#227]
**Describe the bug**
Currently when a candidate is not on the state list we still show how much candidates from this state list went into the parliament.

**To Reproduce**

1. Go to Jens Spahn
2. Click on Wahlchancen
3. Click on Zweitstimme

**Expected behavior**
If the candidate is not on the state list hide the red marked components.

**Screenshots**
![WhatsApp Image 2021-07-30 at 13 23 14](https://user-images.githubusercontent.com/72171703/127646125-88fac177-f9a8-4da9-8418-0801056eee91.jpeg)

**Comment by takahiromitsui** [comment]
Fix at 9487b50
