### ISSUE TITLE
[Bug] Back - Button

### ISSUE THREAD

**Issue by Fingolf6455** [FabianVolkers/face-the-facts-app#234]
**Describe the bug**
"Zurück" is not psrt of the back Button.

**To Reproduce**

1. Go to 'Amthor'
2. Click on 'Wichtigste Abstimungen'
3. See error

**Expected behavior**
When I click on the letters 'zurück' i also come back to the Profilseite.

**Screenshot**
![Screenshot_20210803-125733_Chrome](https://user-images.githubusercontent.com/72171703/128006226-bd43ee07-66c0-4a0b-b26e-92b61aa28dcc.jpg)

**Comment by takahiromitsui** [comment]
Used IonBackButton to unmount the page when the back button is clicked
