### ISSUE TITLE
[Feature] Search: Search Screen

### ISSUE THREAD

**Issue by FabianVolkers** [FabianVolkers/face-the-facts-app#39]
**Is your feature request related to a problem? Please describe.**
Users need the ability to search for candidates if no election poster is close by

**Describe the solution you'd like**
Create a screen based on this design. The search itself can remain to be powered by the abgeordnetenwatch API for now.

![2021-02-17 10 55 16](https://user-images.githubusercontent.com/33686912/108187345-a82e0080-710e-11eb-872b-69b543bec654.jpg)

**Comment by FabianVolkers** [comment]
The existing commits for this issue have been cherry-picked onto branch [39/feature/candidate-search](https://github.com/FaceTheFacts/web/tree/39/feature/candidate-search), so they work seamlessly with the cleaned up develop branch.

**Comment by takahiromitsui** [comment]
The attached photo is an old design and the page doesn't exist.
So, close this branch.
