### ISSUE TITLE
[Feature] Election Chances: Second Vote

### ISSUE THREAD

**Issue by takahiromitsui** [FabianVolkers/face-the-facts-app#41]
**Is your feature request related to a problem? Please describe.**
Users need to understand the information about the second vote.

**Describe the solution you'd like**
I created a second vote list based on the design.

<img width="1115" alt="Screen Shot 2021-02-23 at 15 01 28" src="https://user-images.githubusercontent.com/78789212/108854378-17f92b00-75e8-11eb-8f7e-82df3feb6ad4.png">

**Comment by FabianVolkers** [comment]
Closed in #51, merged into 34/election-chances
