### ISSUE TITLE
[Feature] Election Chances: SegmentButtons

### ISSUE THREAD

**Issue by RichardKruemmel** [FabianVolkers/face-the-facts-app#42]
**Is your feature request related to a problem? Please describe.**
The User should be able to switch between the views of First Vote, Second Vote and Election District on the Election Chances Page.

**Describe the solution you'd like**
Building IonSegment and SegmentButton based on Design
![image](https://user-images.githubusercontent.com/61158193/109053214-c41c3e00-76dc-11eb-8423-00bf60141bcd.png)
![image](https://user-images.githubusercontent.com/61158193/109053343-deeeb280-76dc-11eb-939b-97109df76391.png)

**Comment by FabianVolkers** [comment]
Implemented in #44
