### ISSUE TITLE
[Feature] Header: 

### ISSUE THREAD

**Issue by RichardKruemmel** [FabianVolkers/face-the-facts-app#46]
**Is your feature request related to a problem? Please describe.**
Creating Header containing information about the politician like name, age, party, professional background and current position
**Describe the solution you'd like**
Rebuilding previous Header Component according to new Design

![image](https://user-images.githubusercontent.com/61158193/110316358-e9794800-800a-11eb-9e68-bee4f2582bb7.png)

**Comment by FabianVolkers** [comment]
Closed in #50
